apiVersion: v2
name: jhipster-online
description: "Stack with JHipster Online on Red Hat OpenShift. 
            This Artifact include:
             - JHipster 8.8.0. for generate Spring Boot 3.4.1 projects. 
             - generator-jhipster-quarkus 3.4.0 for generate Quarkus 3.11.1 projects.
             - JDL Studio for add JDL models files by PR on your repo."

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

sources:
  - https://github.com/maximilianoPizarro/jhipster-online-helm-chart
  - https://github.com/redhat-developer-demos/jhipster-online

keywords:
- jhipster
- spring
- openshift

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.33.0"

home: https://maximilianopizarro.github.io/jhipster-online-helm-chart/

maintainers: # (optional)
  - name: Maximiliano Pizarro
    email: maximiliano.pizarro.5@gmail.com
    url: http://www.linkedin.com/in/maximiliano-gregorio-pizarro-consultor-it

icon: https://raw.githubusercontent.com/maximilianoPizarro/jhipster-online-helm-chart/main/rethat-jhipster.png

#dependencies:
#- name: mariadb
#  version: "20.2.2"
#  repository: "oci://registry-1.docker.io/bitnamicharts"