kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  labels:
    {{- include "jhipster-online.labels" . | nindent 4 }}
data:
  default.conf: |-

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
      proxy_pass http://{{ include "jhipster-online.fullname" . }}:8080/;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
    }

    location /jdl-studio/ {
      proxy_pass http://{{ include "jhipster-online.fullname" . }}:8081/;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
    }
