{{- range $name, $worker := .Values.workers }}
{{- if and $worker.enabled (gt (int $worker.replicas) 0) }}
{{- if $worker.image.repository }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jhipster-online.fullname" $ }}-worker-{{ $name | kebabcase }}
  labels:
    {{- include "jhipster-online.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ $name | kebabcase }}
spec:
  replicas: {{ $worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker-{{ $name | kebabcase }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        {{- include "jhipster-online.labels" $ | nindent 8 }}
        app.kubernetes.io/component: worker-{{ $name | kebabcase }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jhipster-online.serviceAccountName" $ }}
      containers:
        - name: jhipster-online
          image: "{{ $worker.image.repository }}:{{ $worker.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
          {{- range $key, $value := $.Values.env }}
            {{- if ne $key "APPLICATION_JHIPSTER-CMD_CMD" }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
            - name: APPLICATION_JHIPSTER-CMD_CMD
              value: {{ $worker.generatorCmd | quote }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with $.Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jhipster-online.fullname" $ }}-worker-{{ $name | kebabcase }}
  labels:
    {{- include "jhipster-online.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ $name | kebabcase }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: worker-{{ $name | kebabcase }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
{{- end }}
